"""Application handler contracts and reference handlers."""

from app.application.handlers.protocols import CommandHandler, QueryHandler
from app.application.handlers.resources import (
    AssignResourceAliasHandler,
    AssignResourceClassificationHandler,
    AssignResourceIdentifierHandler,
    AssignResourceLabelHandler,
    AssignResourceOwnershipHandler,
    AssignResourceRelationshipHandler,
    CreateResourceHandler,
    EnsureResourceExistsHandler,
    FindResourceByAliasHandler,
    FindResourceByIdentifierHandler,
    GetResourceByCanonicalNameHandler,
    GetResourceByIdHandler,
    GetResourceDetailsHandler,
    GetResourceHistoryHandler,
    GetResourceRelationshipsHandler,
    ListResourcesHandler,
    MergeResourceHandler,
    ResolveCanonicalResourceHandler,
    TransitionResourceStateHandler,
)

__all__ = [
    "AssignResourceAliasHandler",
    "AssignResourceClassificationHandler",
    "AssignResourceIdentifierHandler",
    "AssignResourceLabelHandler",
    "AssignResourceOwnershipHandler",
    "AssignResourceRelationshipHandler",
    "CommandHandler",
    "CreateResourceHandler",
    "EnsureResourceExistsHandler",
    "FindResourceByAliasHandler",
    "FindResourceByIdentifierHandler",
    "GetResourceByCanonicalNameHandler",
    "GetResourceByIdHandler",
    "GetResourceDetailsHandler",
    "GetResourceHistoryHandler",
    "GetResourceRelationshipsHandler",
    "ListResourcesHandler",
    "MergeResourceHandler",
    "QueryHandler",
    "ResolveCanonicalResourceHandler",
    "TransitionResourceStateHandler",
]
